apiVersion: apps/v1
kind: Deployment
metadata:
  name: pubsubgo
spec:
  template:
    spec:
      containers:
        - name: pubsubgo
          resources:
            requests:
              memory: "128Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "200m"
          env:
            - name: ENVIRONMENT
              value: "development"
            - name: LOG_LEVEL
              value: "debug"