apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pubsubgo-prod

namePrefix: prod-

resources:
  - ../../base

patchesStrategicMerge:
  - deployment-patch.yaml
  - redis-patch.yaml

replicas:
  - name: pubsubgo
    count: 5
  - name: redis
    count: 3

images:
  - name: pubsubgo
    newTag: latest

configMapGenerator:
  - name: pubsubgo-config
    behavior: replace
    files:
      - config.yaml